export type ProofTool = 'lean4' | 'halmos' | 'foundry'
export type ProofStatus = 'proved' | 'partial' | 'axiom'

export interface ProofConfig {
  id: string
  title: string
  subtitle: string
  abstract: string
  tool: ProofTool
  status: ProofStatus
  theoremCount: number
  sourceUrl: string
  githubUrl: string
  date: string
  authors: string[]
  tags: string[]
  relatedPapers?: string[]
}

export interface SiteConfig {
  name: string
  fullName: string
  description: string
  website: string
  github: string
  primaryColor: string
  secondaryColor: string
  accentColor: string
  logo: string
  proofs: ProofConfig[]
}

export const siteConfig: SiteConfig = {
  name: 'Lux',
  fullName: 'Lux Network',
  description: 'Formal verification of consensus protocols, DeFi invariants, and cryptographic primitives using Lean 4, Halmos, and Foundry.',
  website: 'https://lux.network',
  github: 'https://github.com/luxfi',
  primaryColor: '#3498DB',
  secondaryColor: '#2980B9',
  accentColor: '#E67E22',
  logo: '/logos/lux-logo.svg',
  proofs: [
    // --- Lean 4 Consensus Proofs ---
    {
      id: 'bft-safety',
      title: 'BFT Safety',
      subtitle: 'Quorum Intersection & Honest Majority',
      abstract: 'Formal proof of Byzantine fault tolerance safety properties including quorum intersection, honest majority guarantees, and unique decision thresholds.',
      tool: 'lean4',
      status: 'partial',
      theoremCount: 5,
      sourceUrl: 'https://github.com/luxfi/proofs/blob/main/lean/Consensus/BFT.lean',
      githubUrl: 'https://github.com/luxfi/proofs',
      date: '2025-12-25',
      authors: ['Zach Kelling', 'Woo Bin'],
      tags: ['BFT', 'Safety', 'Quorum', 'Consensus'],
      relatedPapers: ['Lux Consensus Paper'],
    },
    {
      id: 'consensus-safety',
      title: 'Consensus Safety',
      subtitle: 'Main Safety Theorem',
      abstract: 'The central safety theorem proving that no two honest nodes can finalize conflicting decisions under the assumed fault model.',
      tool: 'lean4',
      status: 'proved',
      theoremCount: 1,
      sourceUrl: 'https://github.com/luxfi/proofs/blob/main/lean/Consensus/Safety.lean',
      githubUrl: 'https://github.com/luxfi/proofs',
      date: '2025-12-25',
      authors: ['Zach Kelling', 'Woo Bin'],
      tags: ['Safety', 'Consensus', 'Finality'],
      relatedPapers: ['Lux Consensus Paper'],
    },
    {
      id: 'consensus-liveness',
      title: 'Consensus Liveness',
      subtitle: 'Liveness Under Partial Synchrony',
      abstract: 'Formal proof that the consensus protocol eventually makes progress under partial synchrony assumptions with bounded message delays.',
      tool: 'lean4',
      status: 'proved',
      theoremCount: 1,
      sourceUrl: 'https://github.com/luxfi/proofs/blob/main/lean/Consensus/Liveness.lean',
      githubUrl: 'https://github.com/luxfi/proofs',
      date: '2025-12-25',
      authors: ['Zach Kelling', 'Woo Bin'],
      tags: ['Liveness', 'Partial Synchrony', 'Consensus'],
      relatedPapers: ['Lux Consensus Paper'],
    },
    {
      id: 'wave-protocol',
      title: 'Wave Protocol',
      subtitle: 'Decision Stability & Confidence Monotonicity',
      abstract: 'Three theorems proving decided_stable (finalized decisions never revert), confidence_monotone (confidence only increases), and finalization (termination guarantee).',
      tool: 'lean4',
      status: 'proved',
      theoremCount: 3,
      sourceUrl: 'https://github.com/luxfi/proofs/blob/main/lean/Protocol/Wave.lean',
      githubUrl: 'https://github.com/luxfi/proofs',
      date: '2025-12-25',
      authors: ['Zach Kelling', 'Woo Bin'],
      tags: ['Wave', 'Stability', 'Finalization', 'Protocol'],
      relatedPapers: ['Lux Consensus Paper'],
    },
    {
      id: 'flare-protocol',
      title: 'Flare Protocol',
      subtitle: 'Certificate Skip Exclusivity & Honest Support',
      abstract: 'Three theorems proving cert_skip_exclusive (no conflicting certificates), honest_support (honest nodes back valid certs), and classify_total (complete classification).',
      tool: 'lean4',
      status: 'proved',
      theoremCount: 3,
      sourceUrl: 'https://github.com/luxfi/proofs/blob/main/lean/Protocol/Flare.lean',
      githubUrl: 'https://github.com/luxfi/proofs',
      date: '2025-12-25',
      authors: ['Zach Kelling', 'Woo Bin'],
      tags: ['Flare', 'Certificates', 'Protocol'],
      relatedPapers: ['Lux Consensus Paper'],
    },
    {
      id: 'quasar-protocol',
      title: 'Quasar Protocol',
      subtitle: 'Height Monotonicity & BLS Quorum',
      abstract: 'Three theorems proving height_monotone (finalized height only increases), bls_quorum (BLS signature quorum validity), and dual_sig (dual-certificate consistency).',
      tool: 'lean4',
      status: 'proved',
      theoremCount: 3,
      sourceUrl: 'https://github.com/luxfi/proofs/blob/main/lean/Protocol/Quasar.lean',
      githubUrl: 'https://github.com/luxfi/proofs',
      date: '2025-12-25',
      authors: ['Zach Kelling', 'Woo Bin'],
      tags: ['Quasar', 'BLS', 'Post-Quantum', 'Protocol'],
      relatedPapers: ['Lux Consensus Paper'],
    },
    {
      id: 'ray-protocol',
      title: 'Ray Protocol',
      subtitle: 'Ray Consensus Verification',
      abstract: 'Formal verification of the Ray consensus protocol with two key theorems covering protocol safety and progress guarantees.',
      tool: 'lean4',
      status: 'partial',
      theoremCount: 3,
      sourceUrl: 'https://github.com/luxfi/proofs/blob/main/lean/Protocol/Ray.lean',
      githubUrl: 'https://github.com/luxfi/proofs',
      date: '2025-12-25',
      authors: ['Zach Kelling', 'Woo Bin'],
      tags: ['Ray', 'Consensus', 'Protocol'],
      relatedPapers: ['Lux Consensus Paper'],
    },
    {
      id: 'field-protocol',
      title: 'Field Protocol',
      subtitle: 'Field Consensus Verification',
      abstract: 'Two theorems verifying the Field consensus protocol properties including consistency and termination.',
      tool: 'lean4',
      status: 'proved',
      theoremCount: 2,
      sourceUrl: 'https://github.com/luxfi/proofs/blob/main/lean/Protocol/Field.lean',
      githubUrl: 'https://github.com/luxfi/proofs',
      date: '2025-12-25',
      authors: ['Zach Kelling', 'Woo Bin'],
      tags: ['Field', 'Consensus', 'Protocol'],
      relatedPapers: ['Lux Consensus Paper'],
    },
    {
      id: 'nova-protocol',
      title: 'Nova Protocol',
      subtitle: 'Nova Consensus Verification',
      abstract: 'Two theorems verifying the Nova consensus protocol covering fast-path finality and fallback safety.',
      tool: 'lean4',
      status: 'proved',
      theoremCount: 2,
      sourceUrl: 'https://github.com/luxfi/proofs/blob/main/lean/Protocol/Nova.lean',
      githubUrl: 'https://github.com/luxfi/proofs',
      date: '2025-12-25',
      authors: ['Zach Kelling', 'Woo Bin'],
      tags: ['Nova', 'Consensus', 'Protocol'],
      relatedPapers: ['Lux Consensus Paper'],
    },
    {
      id: 'nebula-protocol',
      title: 'Nebula Protocol',
      subtitle: 'Nebula Consensus Verification',
      abstract: 'Two theorems verifying the Nebula consensus protocol properties for probabilistic finality and convergence.',
      tool: 'lean4',
      status: 'proved',
      theoremCount: 2,
      sourceUrl: 'https://github.com/luxfi/proofs/blob/main/lean/Protocol/Nebula.lean',
      githubUrl: 'https://github.com/luxfi/proofs',
      date: '2025-12-25',
      authors: ['Zach Kelling', 'Woo Bin'],
      tags: ['Nebula', 'Consensus', 'Protocol'],
      relatedPapers: ['Lux Consensus Paper'],
    },
    {
      id: 'photon-protocol',
      title: 'Photon Protocol',
      subtitle: 'Photon Consensus Verification',
      abstract: 'Two theorems verifying the Photon consensus protocol for low-latency finality and message complexity bounds.',
      tool: 'lean4',
      status: 'proved',
      theoremCount: 2,
      sourceUrl: 'https://github.com/luxfi/proofs/blob/main/lean/Protocol/Photon.lean',
      githubUrl: 'https://github.com/luxfi/proofs',
      date: '2025-12-25',
      authors: ['Zach Kelling', 'Woo Bin'],
      tags: ['Photon', 'Consensus', 'Protocol'],
      relatedPapers: ['Lux Consensus Paper'],
    },
    {
      id: 'prism-protocol',
      title: 'Prism Protocol',
      subtitle: 'Prism Consensus Verification',
      abstract: 'Two theorems verifying the Prism consensus protocol properties for parallel block processing and ordering guarantees.',
      tool: 'lean4',
      status: 'proved',
      theoremCount: 2,
      sourceUrl: 'https://github.com/luxfi/proofs/blob/main/lean/Protocol/Prism.lean',
      githubUrl: 'https://github.com/luxfi/proofs',
      date: '2025-12-25',
      authors: ['Zach Kelling', 'Woo Bin'],
      tags: ['Prism', 'Consensus', 'Protocol'],
      relatedPapers: ['Lux Consensus Paper'],
    },
    {
      id: 'bls-cryptography',
      title: 'BLS Cryptography',
      subtitle: 'Bilinearity & Signature Aggregation',
      abstract: 'Three axioms for BLS signature verification with bilinearity proved. Establishes the cryptographic foundation for aggregate signatures used in Quasar consensus.',
      tool: 'lean4',
      status: 'axiom',
      theoremCount: 3,
      sourceUrl: 'https://github.com/luxfi/proofs/blob/main/lean/Crypto/BLS.lean',
      githubUrl: 'https://github.com/luxfi/proofs',
      date: '2025-12-25',
      authors: ['Zach Kelling', 'Woo Bin'],
      tags: ['BLS', 'Cryptography', 'Bilinearity', 'Aggregation'],
      relatedPapers: ['Lux Consensus Paper', 'Lux Bridge Paper'],
    },
    {
      id: 'frost-threshold',
      title: 'FROST Threshold',
      subtitle: 'Schnorr Threshold Signature Axioms',
      abstract: 'Two axioms with real postconditions for FROST threshold signature verification, establishing correctness of t-of-n Schnorr threshold signing.',
      tool: 'lean4',
      status: 'axiom',
      theoremCount: 2,
      sourceUrl: 'https://github.com/luxfi/proofs/blob/main/lean/Crypto/FROST.lean',
      githubUrl: 'https://github.com/luxfi/proofs',
      date: '2025-12-25',
      authors: ['Zach Kelling', 'Woo Bin'],
      tags: ['FROST', 'Threshold', 'Schnorr', 'Cryptography'],
      relatedPapers: ['Lux Consensus Paper', 'Lux Bridge Paper'],
    },
    {
      id: 'ringtail-pq',
      title: 'Ringtail Post-Quantum',
      subtitle: 'Lattice-Based Threshold Signature Axioms',
      abstract: 'Two axioms for Ringtail post-quantum threshold signatures based on lattice cryptography, ensuring quantum resistance for consensus finality.',
      tool: 'lean4',
      status: 'axiom',
      theoremCount: 2,
      sourceUrl: 'https://github.com/luxfi/proofs/blob/main/lean/Crypto/Ringtail.lean',
      githubUrl: 'https://github.com/luxfi/proofs',
      date: '2025-12-25',
      authors: ['Zach Kelling', 'Woo Bin'],
      tags: ['Ringtail', 'Post-Quantum', 'Lattice', 'Threshold'],
      relatedPapers: ['Lux Consensus Paper', 'Lux Bridge Paper'],
    },
    {
      id: 'mldsa-axioms',
      title: 'ML-DSA',
      subtitle: 'Module Lattice Digital Signature Axioms',
      abstract: 'Two axioms for ML-DSA (FIPS 204) post-quantum digital signatures establishing correctness and unforgeability under lattice hardness assumptions.',
      tool: 'lean4',
      status: 'axiom',
      theoremCount: 2,
      sourceUrl: 'https://github.com/luxfi/proofs/blob/main/lean/Crypto/MLDSA.lean',
      githubUrl: 'https://github.com/luxfi/proofs',
      date: '2025-12-25',
      authors: ['Zach Kelling', 'Woo Bin'],
      tags: ['ML-DSA', 'Post-Quantum', 'FIPS 204', 'Signatures'],
      relatedPapers: ['Lux Consensus Paper', 'Lux Bridge Paper'],
    },
    {
      id: 'warp-delivery',
      title: 'Warp Delivery',
      subtitle: 'Cross-Chain Message Delivery Guarantees',
      abstract: 'Three proved theorems plus nonces_monotone for Warp cross-chain messaging, ensuring exactly-once delivery and replay protection.',
      tool: 'lean4',
      status: 'proved',
      theoremCount: 4,
      sourceUrl: 'https://github.com/luxfi/proofs/blob/main/lean/Warp/Delivery.lean',
      githubUrl: 'https://github.com/luxfi/proofs',
      date: '2025-12-27',
      authors: ['Zach Kelling', 'Woo Bin'],
      tags: ['Warp', 'Cross-Chain', 'Delivery', 'Replay Protection'],
      relatedPapers: ['Lux Bridge Paper'],
    },
    {
      id: 'warp-ordering',
      title: 'Warp Ordering',
      subtitle: 'Cross-Chain Message Ordering',
      abstract: 'Two proved theorems for Warp message ordering guarantees, ensuring causal consistency across chains.',
      tool: 'lean4',
      status: 'proved',
      theoremCount: 2,
      sourceUrl: 'https://github.com/luxfi/proofs/blob/main/lean/Warp/Ordering.lean',
      githubUrl: 'https://github.com/luxfi/proofs',
      date: '2025-12-27',
      authors: ['Zach Kelling', 'Woo Bin'],
      tags: ['Warp', 'Ordering', 'Causal Consistency'],
      relatedPapers: ['Lux Bridge Paper'],
    },
    // --- Halmos Symbolic Proofs ---
    {
      id: 'halmos-amm',
      title: 'AMM V2 Invariants',
      subtitle: 'Constant Product & No-Drain Proofs',
      abstract: 'Twelve symbolic proofs verifying AMM V2 invariants including constant product preservation, no-drain guarantees, output bounds, and fee correctness using Halmos symbolic execution.',
      tool: 'halmos',
      status: 'proved',
      theoremCount: 12,
      sourceUrl: 'https://github.com/luxfi/standard/blob/main/test/halmos/HalmosAMM.t.sol',
      githubUrl: 'https://github.com/luxfi/standard/tree/main/test/halmos',
      date: '2025-12-31',
      authors: ['Zach Kelling', 'Woo Bin'],
      tags: ['AMM', 'Constant Product', 'DeFi', 'Symbolic'],
    },
    {
      id: 'halmos-liquidlux',
      title: 'LiquidLUX Vault',
      subtitle: 'Share Inflation Protection & Exchange Rate',
      abstract: 'Nine symbolic proofs for the LiquidLUX vault covering share inflation protection, exchange rate monotonicity, deposit/withdraw symmetry, and fee accounting correctness.',
      tool: 'halmos',
      status: 'proved',
      theoremCount: 9,
      sourceUrl: 'https://github.com/luxfi/standard/blob/main/test/halmos/HalmosLiquidLUX.t.sol',
      githubUrl: 'https://github.com/luxfi/standard/tree/main/test/halmos',
      date: '2025-12-31',
      authors: ['Zach Kelling', 'Woo Bin'],
      tags: ['Vault', 'Staking', 'Inflation', 'Symbolic'],
    },
    {
      id: 'halmos-markets',
      title: 'Markets Lending',
      subtitle: 'Utilization Bounds & Interest Monotonicity',
      abstract: 'Eight symbolic proofs for the Morpho-style lending markets covering utilization bounds, interest rate monotonicity, collateral sufficiency, and liquidation safety.',
      tool: 'halmos',
      status: 'proved',
      theoremCount: 8,
      sourceUrl: 'https://github.com/luxfi/standard/blob/main/test/halmos/HalmosMarkets.t.sol',
      githubUrl: 'https://github.com/luxfi/standard/tree/main/test/halmos',
      date: '2025-12-31',
      authors: ['Zach Kelling', 'Woo Bin'],
      tags: ['Lending', 'Utilization', 'Interest Rate', 'Symbolic'],
    },
    {
      id: 'halmos-e2e',
      title: 'E2E Bridge Safety',
      subtitle: 'Bridge-Deposit-Yield-Teleport Pipeline',
      abstract: 'End-to-end symbolic proofs verifying the complete bridge-deposit-yield-teleport pipeline, ensuring no asset loss across the full DeFi flow.',
      tool: 'halmos',
      status: 'proved',
      theoremCount: 5,
      sourceUrl: 'https://github.com/luxfi/standard/blob/main/test/halmos/HalmosE2E.t.sol',
      githubUrl: 'https://github.com/luxfi/standard/tree/main/test/halmos',
      date: '2025-12-31',
      authors: ['Zach Kelling', 'Woo Bin'],
      tags: ['E2E', 'Bridge', 'Teleport', 'Symbolic'],
    },
    // --- Foundry Invariant Tests ---
    {
      id: 'foundry-invariants',
      title: 'Invariant Test Suite',
      subtitle: '33 Property-Based Fuzz Suites',
      abstract: 'Comprehensive property-based fuzzing across 33 test suites covering AMM, LiquidLUX, Markets, Perps, StableSwap, Staking, Karma, Bridge, Governance, and Treasury protocols.',
      tool: 'foundry',
      status: 'proved',
      theoremCount: 33,
      sourceUrl: 'https://github.com/luxfi/standard/tree/main/test/foundry/invariant',
      githubUrl: 'https://github.com/luxfi/standard/tree/main/test/foundry/invariant',
      date: '2025-12-31',
      authors: ['Zach Kelling', 'Woo Bin'],
      tags: ['Invariant', 'Fuzzing', 'Property-Based', 'Full Stack'],
    },
  ],
}
